# Generated by Django 5.0 on 2024-06-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_remove_comment_active_remove_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
